# 3層ニューラルネットワークの実装

## 適当なニューラルネットワークの実装

In [2]:
import numpy as np

# 入力層
X = np.array([1.0, 0.5])

# 重み
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])

# バイアス用の重み
B1 = np.array([0.1, 0.2, 0.3])

A1 = np.dot(X, W1) + B1
A1

array([0.3, 0.7, 1.1])

In [3]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [4]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
Z2

array([0.62624937, 0.7710107 ])

In [5]:
def identity_function(x):
  return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)
Y

array([0.31682708, 0.69627909])

## まとめ

In [9]:
def init_network():
    return {
        'W1': np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]]),
        'B1': np.array([0.1, 0.2, 0.3]),
        'W2': np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]]),
        'B2': np.array([0.1, 0.2]),
        'W3': np.array([[0.1, 0.3], [0.2, 0.4]]),
        'B3': np.array([0.1, 0.2]),
    }

def forword(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    B1, B2, B3 = network['B1'], network['B2'], network['B3']
    
    A1 = np.dot(x, W1) + B1
    Z1 = sigmoid(A1)
    
    A2 = np.dot(Z1, W2) + B2
    Z2 = sigmoid(A2)
    
    A3 = np.dot(Z2, W3) + B3
    return identity_function(A3)

nw = init_network()
x = np.array([1.0, 0.5])
y = forword(nw, x)

y

array([0.31682708, 0.69627909])