# 行列計算

## 行列の積

In [13]:
import numpy as np

a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [2, 3],
    [4, 5]
])

print("a * b")
print(a * b) # 要素ごとの乗算

print("np.dot(a, b)")
print(np.dot(a, b)) # 内積



a * b
[[ 2  6]
 [12 20]]
np.dot(a, b)
[[10 13]
 [22 29]]


## NN の行列の積

In [11]:
# 入力層行列
x = np.array([1, 2])
# 接続の重み
w = np.array([[1, 3, 5], [2, 4, 6]])
# 2層目への入力
y = np.dot(x, w)

y

array([ 5, 11, 17])